name: CI

on:
   push:
      branches:
         - main
   pull_request:

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [current]

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js and pnpm
           uses: pnpm/action-setup@v2
           with:
              node-version: ${{ matrix.node-version }}
              cache: "pnpm"

         - name: Install dependencies
           run: pnpm install

         - name: Build
           run: pnpm build

         - name: Test
           run: pnpm test
